VERBS =
[
{
cname: "Les verbes réguliers en -er",
verbs:
[
{ inf: "abandonner", tenses: [["abandonne", "abandonnes", "abandonne", "abandonnons", "abandonnez", "abandonnent"]] }, 
{ inf: "accrocher", tenses: [["accroche", "accroches", "accroche", "accrochons", "accrochez", "accrochent"]] }, 
{ inf: "admirer", tenses: [["admire", "admires", "admire", "admirons", "admirez", "admirent"]] }, 
{ inf: "aider", tenses: [["aide", "aides", "aide", "aidons", "aidez", "aident"]] }, 
{ inf: "aimer", tenses: [["aime", "aimes", "aime", "aimons", "aimez", "aiment"]] }, 
{ inf: "allumer", tenses: [["allume", "allumes", "allume", "allumons", "allumez", "allument"]] }, 
{ inf: "amuser", tenses: [["amuse", "amuses", "amuse", "amusons", "amusez", "amusent"]] }, 
{ inf: "apporter", tenses: [["apporte", "apportes", "apporte", "apportons", "apportez", "apportent"]] }, 
{ inf: "arriver", tenses: [["arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"]] }, 
{ inf: "attacher", tenses: [["attache", "attaches", "attache", "attachons", "attachez", "attachent"]] }, 
{ inf: "attirer", tenses: [["attire", "attires", "attire", "attirons", "attirez", "attirent"]] }, 
{ inf: "attraper", tenses: [["attrape", "attrapes", "attrape", "attrapons", "attrapez", "attrapent"]] }, 
{ inf: "avaler", tenses: [["avale", "avales", "avale", "avalons", "avalez", "avalent"]] }, 
{ inf: "avouer", tenses: [["avoue", "avoues", "avoue", "avouons", "avouez", "avouent"]] }, 
{ inf: "briller", tenses: [["brille", "brilles", "brille", "brillons", "brillez", "brillent"]] }, 
{ inf: "cacher", tenses: [["cache", "caches", "cache", "cachons", "cachez", "cachent"]] }, 
{ inf: "chanter", tenses: [["chante", "chantes", "chante", "chantons", "chantez", "chantent"]] }, 
{ inf: "chercher", tenses: [["cherche", "cherches", "cherche", "cherchons", "cherchez", "cherchent"]] }, 
{ inf: "commander", tenses: [["commande", "commandes", "commande", "commandons", "commandez", "commandent"]] }, 
{ inf: "compter", tenses: [["compte", "comptes", "compte", "comptons", "comptez", "comptent"]] }, 
{ inf: "danser", tenses: [["danse", "danses", "danse", "dansons", "dansez", "dansent"]] }, 
{ inf: "fréquenter", tenses: [["fréquente", "fréquentes", "fréquente", "fréquentons", "fréquentez", "fréquentent"]] }, 
{ inf: "demander", tenses: [["demande", "demandes", "demande", "demandons", "demandez", "demandent"]] }, 
{ inf: "dîner", tenses: [["dine", "dines", "dine", "dinons", "dinez", "dinent"]] }, 
{ inf: "échapper", tenses: [["échappe", "échappes", "échappe", "échappons", "échappez", "échappent"]] }, 
{ inf: "échouer", tenses: [["échoue", "échoues", "échoue", "échouons", "échouez", "échouent"]] }, 
{ inf: "écouter", tenses: [["écoute", "écoutes", "écoute", "écoutons", "écoutez", "écoutent"]] }, 
{ inf: "écraser", tenses: [["écrase", "écrases", "écrase", "écrasons", "écrasez", "écrasent"]] }, 
{ inf: "embrasser", tenses: [["embrasse", "embrasses", "embrasse", "embrassons", "embrassez", "embrassent"]] }, 
{ inf: "emporter", tenses: [["emporte", "emportes", "emporte", "emportons", "emportez", "emportent"]] }, 
{ inf: "emprunter", tenses: [["emprunte", "empruntes", "emprunte", "empruntons", "empruntez", "empruntent"]] }, 
{ inf: "enseigner", tenses: [["enseigne", "enseignes", "enseigne", "enseignons", "enseignez", "enseignent"]] }, 
{ inf: "entourer", tenses: [["entoure", "entoures", "entoure", "entourons", "entourez", "entourent"]] }, 
{ inf: "entrer", tenses: [["entre", "entres", "entre", "entrons", "entrez", "entrent"]] }, 
{ inf: "épouser", tenses: [["épouse", "épouses", "épouse", "épousons", "épousez", "épousent"]] }, 
{ inf: "étudier", tenses: [["étudie", "étudies", "étudie", "étudions", "étudiez", "étudient"]] }, 
{ inf: "fermer", tenses: [["ferme", "fermes", "ferme", "fermons", "fermez", "ferment"]] }, 
{ inf: "décider", tenses: [["decide", "decides", "decide", "decidons", "decidez", "decident"]] }, 
{ inf: "dessiner", tenses: [["dessine", "dessines", "dessine", "dessinons", "dessinez", "dessinent"]] }, 
{ inf: "habiter", tenses: [["habite", "habites", "habite", "habitons", "habitez", "habitent"]] }, 
{ inf: "imaginer", tenses: [["imagine", "imagines", "imagine", "imaginons", "imaginez", "imaginent"]] }, 
{ inf: "inspirer", tenses: [["inspire", "inspires", "inspire", "inspirons", "inspirez", "inspirent"]] }, 
{ inf: "inviter", tenses: [["invite", "invites", "invite", "invitons", "invitez", "invitent"]] }, 
{ inf: "jouer", tenses: [["joue", "joues", "joue", "jouons", "jouez", "jouent"]] }, 
{ inf: "laver", tenses: [["lave", "laves", "lave", "lavons", "lavez", "lavent"]] }, 
{ inf: "louer", tenses: [["loue", "loues", "loue", "louons", "louez", "louent"]] }, 
{ inf: "travailler", tenses: [["travaille", "travailles", "travaille", "travaillons", "travaillez", "travaillent"]] }, 
{ inf: "traverser", tenses: [["traverse", "traverses", "traverse", "traversons", "traversez", "traversent"]] }, 
{ inf: "expliquer", tenses: [["explique", "expliques", "explique", "expliquons", "expliquez", "expliquent"]] }, 
{ inf: "exprimer", tenses: [["exprime", "exprimes", "exprime", "exprimons", "exprimez", "expriment"]] }, 
{ inf: "fouiller", tenses: [["fouille", "fouilles", "fouille", "fouillons", "fouillez", "fouillent"]] }, 
{ inf: "marcher", tenses: [["marche", "marches", "marche", "marchons", "marchez", "marchent"]] }, 
{ inf: "gagner", tenses: [["gagne", "gagnes", "gagne", "gagnons", "gagnez", "gagnent"]] }, 
{ inf: "garder", tenses: [["garde", "gardes", "garde", "gardons", "gardez", "gardent"]] }, 
{ inf: "goûter", tenses: [["goûte", "goûtes", "goûte", "goûtons", "goûtez", "goûtent"]] }, 
{ inf: "organiser", tenses: [["organise", "organises", "organise", "organisons", "organisez", "organisent"]] }, 
{ inf: "oser", tenses: [["ose", "oses", "ose", "osons", "osez", "osent"]] }, 
{ inf: "oublier", tenses: [["oublie", "oublies", "oublie", "oublions", "oubliez", "oublient"]] }, 
{ inf: "passer", tenses: [["passe", "passes", "passe", "passons", "passez", "passent"]] }, 
{ inf: "irriter", tenses: [["irrite", "irrites", "irrite", "irritons", "irritez", "irritent"]] }, 
{ inf: "poser", tenses: [["pose", "poses", "pose", "posons", "posez", "posent"]] }, 
{ inf: "laisser", tenses: [["laisse", "laisses", "laisse", "laissons", "laissez", "laissent"]] }, 
{ inf: "présenter", tenses: [["présente", "présentes", "présente", "présentons", "présentez", "présentent"]] }, 
{ inf: "prêter", tenses: [["prête", "prêtes", "prête", "prêtons", "prêtez", "prêtent"]] }, 
{ inf: "toucher", tenses: [["touche", "touches", "touche", "touchons", "touchez", "touchent"]] }, 
{ inf: "tromper", tenses: [["trompe", "trompes", "trompe", "trompons", "trompez", "trompent"]] }, 
{ inf: "utiliser", tenses: [["utilise", "utilises", "utilise", "utilisons", "utilisez", "utilisent"]] }, 
{ inf: "visiter", tenses: [["visite", "visites", "visite", "visitons", "visitez", "visitent"]] }, 
{ inf: "quitter", tenses: [["quitte", "quittes", "quitte", "quittons", "quittez", "quittent"]] }, 
{ inf: "raconter", tenses: [["raconte", "racontes", "raconte", "racontons", "racontez", "racontent"]] }, 
{ inf: "monter", tenses: [["monte", "montes", "monte", "montons", "montez", "montent"]] }, 
{ inf: "montrer", tenses: [["montre", "montres", "montre", "montrons", "montrez", "montrent"]] }, 
{ inf: "rentrer", tenses: [["rentre", "rentres", "rentre", "rentrons", "rentrez", "rentrent"]] }, 
{ inf: "rester", tenses: [["reste", "restes", "reste", "restons", "restez", "restent"]] }, 
{ inf: "retourner", tenses: [["retourne", "retournes", "retourne", "retournons", "retournez", "retournent"]] }, 
{ inf: "retrouver", tenses: [["retrouve", "retrouves", "retrouve", "retrouvons", "retrouvez", "retrouvent"]] }, 
{ inf: "porter", tenses: [["porte", "portes", "porte", "portons", "portez", "portent"]] }, 
{ inf: "sauter", tenses: [["saute", "sautes", "saute", "sautons", "sautez", "sautent"]] }, 
{ inf: "préparer", tenses: [["prépare", "prépares", "prépare", "préparons", "préparez", "préparent"]] }, 
{ inf: "tomber", tenses: [["tombe", "tombes", "tombe", "tombons", "tombez", "tombent"]] }, 
{ inf: "refuser", tenses: [["refuse", "refuses", "refuse", "refusons", "refusez", "refusent"]] }, 
{ inf: "regarder", tenses: [["regarde", "regardes", "regarde", "regardons", "regardez", "regardent"]] }, 
{ inf: "opposer", tenses: [["oppose", "opposes", "oppose", "opposons", "opposez", "opposent"]] }, 
{ inf: "saluer", tenses: [["salue", "salues", "salue", "saluons", "saluez", "saluent"]] }, 
{ inf: "sonner", tenses: [["sonne", "sonnes", "sonne", "sonnons", "sonnez", "sonnent"]] }, 
{ inf: "téléphoner", tenses: [["téléphone", "téléphones", "téléphone", "téléphonons", "téléphonez", "téléphonent"]] },
{ inf: "rencontrer", tenses: [["rencontre", "rencontres", "rencontre", "rencontrons", "rencontrez", "rencontrent"]] }
]
},

{
cname: "Les verbes irréguliers en -er",
verbs:
[
{ inf: "commencer", tenses: [["commence", "commences", "commence", "commençons", "commencez", "commencent"]] },
{ inf: "avancer", tenses: [["avance", "avances", "avance", "avançons", "avancez", "avancent"]] }, 
{ inf: "divorcer", tenses: [["divorce", "divorces", "divorce", "divorçons", "divorcez", "divorcent"]] }, 
{ inf: "se fiancer", tenses: [["fiance", "fiances", "fiance", "fiançons", "fiancez", "fiancent"]] }, 
{ inf: "lancer", tenses: [["lance", "lances", "lance", "lançons", "lancez", "lancent"]] }, 
{ inf: "menacer", tenses: [["menace", "menaces", "menace", "menaçons", "menacez", "menacent"]] },
{ inf: "arranger", tenses: [["arrange", "arranges", "arrange", "arrangeons", "arrangez", "arrangent"]] }, 
{ inf: "charger", tenses: [["charge", "charges", "charge", "chargeons", "chargez", "chargent"]] }, 
{ inf: "dégager", tenses: [["dégage", "dégages", "dégage", "dégageons", "dégagez", "dégagent"]] }, 
{ inf: "diriger", tenses: [["dirige", "diriges", "dirige", "dirigeons", "dirigez", "dirigent"]] }, 
{ inf: "interroger", tenses: [["interroge", "interroges", "interroge", "interrogeons", "interrogez", "interrogent"]] },
{ inf: "manger", tenses: [["mange", "manges", "mange", "mangeons", "mangez", "mangent"]] }, 
{ inf: "négliger", tenses: [["néglige", "négliges", "néglige", "négligeons", "négligez", "négligent"]] }, 
{ inf: "obliger", tenses: [["oblige", "obliges", "oblige", "obligeons", "obligez", "obligent"]] }, 
{ inf: "plonger", tenses: [["plonge", "plonges", "plonge", "plongeons", "plongez", "plongent"]] }, 
{ inf: "ranger", tenses: [["range", "ranges", "range", "rangeons", "rangez", "rangent"]] }, 
{ inf: "voyager", tenses: [["voyage", "voyages", "voyage", "voyageons", "voyagez", "voyagent"]] }, 
{ inf: "corriger", tenses: [["corrige", "corriges", "corrige", "corrigeons", "corrigez", "corrigent"]] }, 
{ inf: "mélanger", tenses: [["mélange", "mélanges", "mélange", "mélangeons", "mélangez", "mélangent"]] }, 
{ inf: "protéger", tenses: [["protège", "protèges", "protège", "protégeons", "protégez", "protègent"]] }, 
{ inf: "changer", tenses: [["change", "changes", "change", "changeons", "changez", "changent"]] }, 
{ inf: "déranger", tenses: [["dérange", "déranges", "dérange", "dérangeons", "dérangez", "dérangent"]] }, 
{ inf: "exiger", tenses: [["exige", "exiges", "exige", "exigeons", "exigez", "exigent"]] }, 
{ inf: "engager", tenses: [["engage", "engages", "engage", "engageons", "engagez", "engagent"]] }, 
{ inf: "juger", tenses: [["juge", "juges", "juge", "jugeons", "jugez", "jugent"]] }, 
{ inf: "partager", tenses: [["partage", "partages", "partage", "partageons", "partagez", "partagent"]] }, 
{ inf: "venger", tenses: [["venge", "venges", "venge", "vengeons", "vengez", "vengent"]] }, 
{ inf: "balayer", tenses: [["balaye", "balayes", "balaye", "balayons", "balayez", "balayent"]] }, 
{ inf: "employer", tenses: [["emploie", "emploies", "emploie", "employons", "employez", "emploient"]] }, 
{ inf: "ennuyer", tenses: [["ennuie", "ennuies", "ennuie", "ennuyons", "ennuyez", "ennuient"]] }, 
{ inf: "essayer", tenses: [["essaye", "essayes", "essaye", "essayons", "essayez", "essayent"]] }, 
{ inf: "essuyer", tenses: [["essuie", "essuies", "essuie", "essuyons", "essuyez", "essuient"]] }, 
{ inf: "nettoyer", tenses: [["nettoie", "nettoies", "nettoie", "nettoyons", "nettoyez", "nettoient"]] }, 
{ inf: "payer", tenses: [["paye", "payes", "paye", "payons", "payez", "payent"]] }, 
{ inf: "renvoyer", tenses: [["renvoie", "renvoies", "renvoie", "renvoyons", "renvoyez", "renvoient"]] }, 
{ inf: "achever", tenses: [["achève", "achèves", "achève", "achevons", "achevez", "achèvent"]] }, 
{ inf: "amener", tenses: [["amène", "amènes", "amène", "amenons", "amenez", "amènent"]] }, 
{ inf: "élever", tenses: [["élève", "élèves", "élève", "élevons", "élevez", "élèvent"]] }, 
{ inf: "emmener", tenses: [["emmène", "emmènes", "emmène", "emmenons", "emmenez", "emmènent"]] }, 
{ inf: "enlever", tenses: [["enlève", "enlèves", "enlève", "enlevons", "enlevez", "enlèvent"]] }, 
{ inf: "geler", tenses: [["gèle", "gèles", "gèle", "gelons", "gelez", "gèlent"]] }, 
{ inf: "lever", tenses: [["lève", "lèves", "lève", "levons", "levez", "lèvent"]] }, 
{ inf: "mener", tenses: [["mène", "mènes", "mène", "menons", "menez", "mènent"]] }, 
{ inf: "peser", tenses: [["pèse", "pèses", "pèse", "pesons", "pesez", "pèsent"]] }, 
{ inf: "promener", tenses: [["promène", "promènes", "promène", "promenons", "promenez", "promènent"]] }, 
{ inf: "appeler", tenses: [["appelle", "appelles", "appelle", "appelons", "appelez", "appellent"]] }, 
{ inf: "épousseter", tenses: [["époussette", "époussettes", "époussette", "époussetons", "époussetez", "époussettent"]] }, 
{ inf: "empaqueter", tenses: [["empaquette", "empaquettes", "empaquette", "empaquetons", "empaquetez", "empaquettent"]] }, 
{ inf: "étinceler", tenses: [["étincelle", "étincelles", "étincelle", "étincelons", "étincelez", "étincellent"]] }, 
{ inf: "jeter", tenses: [["jette", "jettes", "jette", "jetons", "jetez", "jettent"]] }, 
{ inf: "rappeler", tenses: [["rappelle", "rappelles", "rappelle", "rappelons", "rappelez", "rappellent"]] }, 
{ inf: "rejeter", tenses: [["rejette", "rejettes", "rejette", "rejetons", "rejetez", "rejettent"]] }, 
{ inf: "accelérér", tenses: [["accélère", "accélères", "accélère", "accélérons", "accélérez", "accélèrent"]] }, 
{ inf: "céder", tenses: [["cède", "cèdes", "cède", "cédons", "cédez", "cèdent"]] }, 
{ inf: "célébrer", tenses: [["célèbre", "célèbres", "célèbre", "célébrons", "célébrez", "célèbrent"]] }, 
{ inf: "compléter", tenses: [["complète", "complètes", "complète", "complétons", "complétez", "complètent"]] }, 
{ inf: "considérer", tenses: [["considère", "considères", "considère", "considérons", "considérez", "considèrent"]] }, 
{ inf: "s'inquiéter", tenses: [["inquiète", "inquiètes", "inquiète", "inquiétons", "inquiétez", "inquiètent"]] }, 
{ inf: "interpréter", tenses: [["interprète", "interprètes", "interprète", "interprétons", "interprétez", "interprètent"]] }, 
{ inf: "posséder", tenses: [["possède", "possèdes", "possède", "possédons", "possédez", "possèdent"]] }, 
{ inf: "précéder", tenses: [["précède", "précèdes", "précède", "précédons", "précédez", "précèdent"]] }, 
{ inf: "préférer", tenses: [["préfère", "préfères", "préfère", "préférons", "préférez", "préfèrent"]] }, 
{ inf: "protéger", tenses: [["protège", "protèges", "protège", "protégeons", "protégez", "protègent"]] }, 
{ inf: "répéter", tenses: [["répète", "répètes", "répète", "répétons", "répétez", "répètent"]] }, 
{ inf: "sécher", tenses: [["sèche", "sèches", "sèche", "séchons", "séchez", "sèchent"]] }, 
{ inf: "suggérer", tenses: [["suggère", "suggères", "suggère", "suggérons", "suggérez", "suggèrent"]] }
]
}
];
